name: flex_year_tablet
description: Flexyear tablet app.

publish_to: 'none'

version: 1.0.0+6

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  awesome_notifications: ^0.0.6
  bestfriend: 
    path: ./packages/bestfriend
  cached_network_image: ^3.2.0
  connectivity_plus: ^2.1.0
  cupertino_icons: ^1.0.2
  device_preview: ^0.7.0
  dio: ^4.0.3
  # firebase_core: ^2.8.0
  # firebase_messaging: ^14.3.0
  flex_color_scheme: ^4.2.0
  flutter:
    sdk: flutter
  freezed_annotation: ^0.14.2
  google_fonts: ^2.1.0
  image_cropper: ^1.4.1
  image_picker: ^0.8.4
  intl: ^0.17.0
  json_annotation: ^4.0.0
  material_design_icons_flutter: ^5.0.6295
  pin_code_fields: ^7.3.0
  rive: ^0.9.0
  local_auth:  ^1.1.7
  flutter_slidable: ^1.3.0
  nepali_date_picker: ^5.1.0
  curved_navigation_bar: ^1.0.3
  package_info_plus: ^1.4.2
  flutter_neumorphic: ^3.2.0
  liquid_progress_indicator: ^0.4.0
  shimmer: ^2.0.0
  provider: ^5.0.0
  delayed_display: ^2.0.0
  flutter_localization: ^0.1.9
  table_calendar: ^3.0.8
  clean_nepali_calendar: ^2.0.1
 



 
dev_dependencies:
  build_runner: null
  flutter_lints: ^1.0.4
  freezed: null
  json_serializable: ^4.1.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
