// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       throw UnsupportedError(
//         'DefaultFirebaseOptions have not been configured for web - '
//         'you can reconfigure this by running the FlutterFire CLI again.',
//       );
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyCTe2qHir7-qjSX56msWzOyE_fUOFUuHHg',
//     appId: '1:830101525264:android:3f7d72bcf8bd5574cccb95',
//     messagingSenderId: '830101525264',
//     projectId: 'flexyear-7500d',
//     databaseURL: 'https://flexyear-7500d.firebaseio.com',
//     storageBucket: 'flexyear-7500d.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyBaqPNrXRfwt8iCzEY9BtXnEE54S1dbj-0',
//     appId: '1:830101525264:ios:9d0816a8f8c324dacccb95',
//     messagingSenderId: '830101525264',
//     projectId: 'flexyear-7500d',
//     databaseURL: 'https://flexyear-7500d.firebaseio.com',
//     storageBucket: 'flexyear-7500d.appspot.com',
//     androidClientId:
//         '830101525264-1i41oevsv31vvphgep9ajde18ql6agpo.apps.googleusercontent.com',
//     iosClientId:
//         '830101525264-tt0vlfj4ocotf5j1v438oiec924hr5a5.apps.googleusercontent.com',
//     iosBundleId: 'work.flexyear.flexYearTablet',
//   );
// }
